"""
This is a setup.py script generated by py2applet

Usage:
    set filepath.txt to no
    python3 setup.py py2app -d ../
    file available in dist/MacOS
"""

from setuptools import setup
import distutils.command.build

# Override build command
class BuildCommand(distutils.command.build.build):
    def initialize_options(self):
        distutils.command.build.build.initialize_options(self)
        self.build_base = '../build'



APP = ['main.py']
DATA_FILES = ['filepath.txt']
OPTIONS = {}

setup(
    name='Personal Finance Dashboard',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    cmdclass={'build': BuildCommand}
)
